---
# tasks file for ntp (CentOS specific)

- name: Install ntp
  yum: name={{ item }} state=present
  with_items:
    - ntp
    - ntpdate
  tags: ntp

- name: Create ntp configuration file
  template: >
    src=ntp.conf.j2
    dest=/etc/ntp.conf
    owner=root
    group=root
    mode=0644
  notify: restart ntp
  tags: ntp

- name: Start ntp service
  service: name={{ ntp_service_name }} state=started enabled=yes
  tags: ntp
