---
# tasks file for ntp

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: ntp

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: ntp

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: ntp

- name: Create ntp configuration file
  template: >
    src=ntp.conf.j2
    dest=/etc/ntp.conf
    owner=root
    group=root
    mode=0644
  notify: restart ntp
  tags: ntp

- name: Ensure ntp service is started and enabled on boot
  service: name={{ ntp_service_name }} state=started enabled=yes
  tags: ntp
