---
# tasks file for ntp

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: ntp

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: ntp

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: ntp
