---
# tasks file for ntp (Ubuntu specific)

- name: Install ntp packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ ntp_packages }}"
  tags:
    - ntp
